// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_Hx7n24o_7QqtkuVOJxch2dcY97aJT70',
    appId: '1:665095074853:web:c290f8569c2637e89abbcc',
    messagingSenderId: '665095074853',
    projectId: 'libri-bf04d',
    authDomain: 'libri-bf04d.firebaseapp.com',
    storageBucket: 'libri-bf04d.firebasestorage.app',
    measurementId: 'G-EXGE9KZFLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1lWpfVUqlSnjMjiHvNq7IG9iAVdECpQ',
    appId: '1:665095074853:android:ae719419ca41ff1a9abbcc',
    messagingSenderId: '665095074853',
    projectId: 'libri-bf04d',
    storageBucket: 'libri-bf04d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkSkvSmbodg4sLNPD_RI36ME5ss5LnDPU',
    appId: '1:665095074853:ios:5b057975323c29829abbcc',
    messagingSenderId: '665095074853',
    projectId: 'libri-bf04d',
    storageBucket: 'libri-bf04d.firebasestorage.app',
    iosBundleId: 'com.example.libri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkSkvSmbodg4sLNPD_RI36ME5ss5LnDPU',
    appId: '1:665095074853:ios:5b057975323c29829abbcc',
    messagingSenderId: '665095074853',
    projectId: 'libri-bf04d',
    storageBucket: 'libri-bf04d.firebasestorage.app',
    iosBundleId: 'com.example.libri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_Hx7n24o_7QqtkuVOJxch2dcY97aJT70',
    appId: '1:665095074853:web:ce88b26f54bde9179abbcc',
    messagingSenderId: '665095074853',
    projectId: 'libri-bf04d',
    authDomain: 'libri-bf04d.firebaseapp.com',
    storageBucket: 'libri-bf04d.firebasestorage.app',
    measurementId: 'G-98TJ1549XD',
  );
}
